### ISSUE TITLE
Run time limits

### ISSUE THREAD

**Issue by Geal** [flynn/biscuit-go#42]
cf https://github.com/CleverCloud/biscuit/issues/53 I added some limits to the Datalog engine execution in the Rust and Java version, to limit the number of facts ( memory usage), iterations and run time. It would be a good idea to add them ;)

**Comment by daeMOn63** [comment]
Yep, definitively a good idea to add this. I've added some restriction on the biscuit size in one of our clients, but this extra run time limit is better.
