### ISSUE TITLE
text syntax changes

### ISSUE THREAD

**Issue by Geal** [flynn/biscuit-go#43]
I'm cleaning up the text syntax, so there are changes to follow here https://github.com/CleverCloud/biscuit/issues/54
For now, it's mainly about removing the `*` prefix in rule and caveat heads, an allowing heads with 0 terms, which simplifies caveats.
If you don't have time to take care of it, I'll see to send a PR in a week.

**Comment by daeMOn63** [comment]
Thanks ! I'll have limited availability in coming weeks, but shouldn't be an issue to integrate. If you'd like to have a go at it, feel free to start from #40 which contains latest work on our parser / grammar.
